version: 1
storage_merch:
  url: http://127.0.0.1:8090/merch-inventory
storage_food:
  url: http://127.0.0.1:8090/food-inventory

services:
  receiverStats: http://kafka.westus3.cloudapp.azure.com/receiver/health
  storageStats:  http://kafka.westus3.cloudapp.azure.com/storage/health
  processingStats:  http://kafka.westus3.cloudapp.azure.com/processing/health
  auditStats:  http://kafka.westus3.cloudapp.azure.com/audit/health
