version: 1
storage_merch:
  url: http://127.0.0.1:8090/merch-inventory
storage_food:
  url: http://127.0.0.1:8090/food-inventory

services:
  receiverStats: http://kafka.westus3.cloudapp.azure.com:8080/health
  storageStats:  http://kafka.westus3.cloudapp.azure.com:8090/health
  processingStats:  http://kafka.westus3.cloudapp.azure.com:8100/health
  auditStats:  http://kafka.westus3.cloudapp.azure.com:8110/health
